# Generated by Django 3.0.4 on 2020-03-29 17:16

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200329_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag',
            field=models.CharField(max_length=50, unique=True, validators=[core.validators.HashTagValidator()]),
        ),
    ]
