# Generated by Django 3.0.4 on 2020-03-29 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200329_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='hashtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.HashTag'),
        ),
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Place'),
        ),
        migrations.AlterField(
            model_name='video',
            name='hashtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.HashTag'),
        ),
        migrations.AlterField(
            model_name='video',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Place'),
        ),
    ]
