# Generated by Django 3.0.4 on 2020-05-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200330_1259'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videolike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='videolike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videolike',
            name='video',
        ),
        migrations.DeleteModel(
            name='ImageLike',
        ),
        migrations.DeleteModel(
            name='VideoLike',
        ),
    ]
