# Generated by Django 3.0.4 on 2020-05-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200506_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_amount', models.PositiveIntegerField()),
                ('video_amount', models.PositiveIntegerField()),
                ('video_views_amount', models.PositiveIntegerField()),
                ('user_amount', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
