# Generated by Django 3.0.4 on 2020-05-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='likes_amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
