# Generated by Django 3.0.4 on 2020-05-06 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_profile_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='chats',
        ),
    ]
